module "foundation" {
  source = "../../modules/foundation"

  tenancy_ocid                               = var.tenancy_ocid
  parent_compartment_ocid                    = var.parent_compartment_ocid
  region                                     = var.region
  environment                                = "staging"
  ssh_public_key                             = var.ssh_public_key
  availability_domain                        = var.availability_domain
  backend_image_ocid                         = var.backend_image_ocid
  backend_shape                              = var.backend_shape
  backend_ocpus                              = var.backend_ocpus
  backend_memory_gbs                         = var.backend_memory_gbs
  frontend_bucket_access_type                = var.frontend_bucket_access_type
  alarm_email                                = var.alarm_email
  enable_knowledge_refresh_scheduler         = var.enable_knowledge_refresh_scheduler
  knowledge_refresh_function_image           = var.knowledge_refresh_function_image
  knowledge_refresh_release_cron             = var.knowledge_refresh_release_cron
  knowledge_refresh_stable_docs_cron         = var.knowledge_refresh_stable_docs_cron
  knowledge_refresh_function_memory_mbs      = var.knowledge_refresh_function_memory_mbs
  knowledge_refresh_function_timeout_seconds = var.knowledge_refresh_function_timeout_seconds
  deployment_profile                         = var.deployment_profile
  operational_diagnostics_enabled            = var.operational_diagnostics_enabled
  oci_connectivity_check_enabled             = var.oci_connectivity_check_enabled
  enable_api_gateway                         = var.enable_api_gateway
  api_gateway_path_prefix                    = var.api_gateway_path_prefix
  oci_devops_project_ocid                    = var.oci_devops_project_ocid
  oci_devops_deploy_pipeline_ocid            = var.oci_devops_deploy_pipeline_ocid
}
